ip2:
  47.96.41.135

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip2}:1225/up?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 12345678Az!
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: ${ip2}
      port: 6379
      password: 1225zjzj
      database: 0
      lettuce:
        pool:
          min-idle: 10
          max-idle: 100
          max-active: 100
          max-wait: 10000